version: '3.8'

services:
  mysql:
    image: bitnami/mysql:latest
    environment:      
      - MYSQL_ROOT_PASSWORD=docker           # Permite o uso de uma senha vazia
      - MYSQL_USER=docker                 # Nome do usuário customizado
      - MYSQL_PASSWORD=docker             # Senha do usuário customizado
      - MYSQL_DATABASE=api-blis           # Nome do banco de dados que será criado
    ports:
      - "3306:3306"                       # Mapeia a porta 3306 do contêiner para a máquina local
    volumes:
      - mysql_data:/bitnami/mysql  # Volume persistente para dados do MySQL
      - ./scripts:/docker-entrypoint-initdb.d  # Volume para scripts de inicialização
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
